const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923119170645" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923119170645";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "true"
global.save_status = process.env.AUTO_SAVE_STATUS || "true"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "all";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Omi",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "Omi-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Omi",

  sessionName:process.env.SESSION_ID || "SUHAIL_02_45_09_12_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTkyLFxuICAgICAgICA4MSxcbiAgICAgICAgMTI3LFxuICAgICAgICA4OSxcbiAgICAgICAgMTc0LFxuICAgICAgICAyMzUsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMzMsXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTM1LFxuICAgICAgICAxNTMsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxMTYsXG4gICAgICAgIDI0OCxcbiAgICAgICAgMTUzLFxuICAgICAgICAxNjMsXG4gICAgICAgIDc0LFxuICAgICAgICAxNixcbiAgICAgICAgMjA1LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTAsXG4gICAgICAgIDE0LFxuICAgICAgICAyMDQsXG4gICAgICAgIDMzLFxuICAgICAgICA2MCxcbiAgICAgICAgMTk4LFxuICAgICAgICAxNDUsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMTEyLFxuICAgICAgICAxMDhcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjQyLFxuICAgICAgICAxLFxuICAgICAgICA0LFxuICAgICAgICA5MyxcbiAgICAgICAgNCxcbiAgICAgICAgMjA0LFxuICAgICAgICAyMixcbiAgICAgICAgMTc5LFxuICAgICAgICAxNzEsXG4gICAgICAgIDIyNyxcbiAgICAgICAgOTksXG4gICAgICAgIDE1NyxcbiAgICAgICAgNzcsXG4gICAgICAgIDkxLFxuICAgICAgICAxMCxcbiAgICAgICAgMTg2LFxuICAgICAgICA1MCxcbiAgICAgICAgMjEsXG4gICAgICAgIDI1NCxcbiAgICAgICAgMTksXG4gICAgICAgIDEwNCxcbiAgICAgICAgNzAsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTEzLFxuICAgICAgICAxODYsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMjM3LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE0NCxcbiAgICAgICAgNzUsXG4gICAgICAgIDIzNCxcbiAgICAgICAgNFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTIwLFxuICAgICAgICAxMzksXG4gICAgICAgIDMzLFxuICAgICAgICA3NSxcbiAgICAgICAgMjksXG4gICAgICAgIDIzMSxcbiAgICAgICAgNDAsXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjAyLFxuICAgICAgICA3MSxcbiAgICAgICAgMTU3LFxuICAgICAgICA5NyxcbiAgICAgICAgNTgsXG4gICAgICAgIDkxLFxuICAgICAgICAxNjYsXG4gICAgICAgIDIzMSxcbiAgICAgICAgODUsXG4gICAgICAgIDExMCxcbiAgICAgICAgMjYsXG4gICAgICAgIDExMixcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNTcsXG4gICAgICAgIDEzMSxcbiAgICAgICAgOTEsXG4gICAgICAgIDQxLFxuICAgICAgICA0OSxcbiAgICAgICAgODQsXG4gICAgICAgIDIwMSxcbiAgICAgICAgODgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMjI5LFxuICAgICAgICAxMjBcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTA2LFxuICAgICAgICAxNzksXG4gICAgICAgIDIzMixcbiAgICAgICAgMTgxLFxuICAgICAgICAxMjUsXG4gICAgICAgIDE1LFxuICAgICAgICAxNjksXG4gICAgICAgIDIxMyxcbiAgICAgICAgMjM1LFxuICAgICAgICA1NyxcbiAgICAgICAgNzMsXG4gICAgICAgIDc3LFxuICAgICAgICA5NyxcbiAgICAgICAgMTAsXG4gICAgICAgIDkzLFxuICAgICAgICA3NyxcbiAgICAgICAgMjA2LFxuICAgICAgICAxMDksXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTExLFxuICAgICAgICAxMzgsXG4gICAgICAgIDU2LFxuICAgICAgICAxMyxcbiAgICAgICAgMTI3LFxuICAgICAgICA5NSxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNzQsXG4gICAgICAgIDY1LFxuICAgICAgICAyNSxcbiAgICAgICAgMTA3LFxuICAgICAgICAxNSxcbiAgICAgICAgNDVcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxMyxcbiAgICAgICAgMTMsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxOTAsXG4gICAgICAgIDMwLFxuICAgICAgICAxNjcsXG4gICAgICAgIDIwOCxcbiAgICAgICAgMTM0LFxuICAgICAgICAxNzQsXG4gICAgICAgIDEyOSxcbiAgICAgICAgNjUsXG4gICAgICAgIDU4LFxuICAgICAgICAxNjQsXG4gICAgICAgIDUzLFxuICAgICAgICA0MyxcbiAgICAgICAgODEsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTA4LFxuICAgICAgICAxMjcsXG4gICAgICAgIDE3NSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxNSxcbiAgICAgICAgMjAsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjQ1LFxuICAgICAgICAyMTYsXG4gICAgICAgIDI0NyxcbiAgICAgICAgMSxcbiAgICAgICAgMTE3XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTUxLFxuICAgICAgICAyMjAsXG4gICAgICAgIDQwLFxuICAgICAgICAxMjAsXG4gICAgICAgIDEzLFxuICAgICAgICAxNjYsXG4gICAgICAgIDI1MixcbiAgICAgICAgMjksXG4gICAgICAgIDE0MCxcbiAgICAgICAgMjI4LFxuICAgICAgICAyMCxcbiAgICAgICAgMzIsXG4gICAgICAgIDY3LFxuICAgICAgICAxMDAsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMTQwLFxuICAgICAgICAxOSxcbiAgICAgICAgMjQ2LFxuICAgICAgICA2MixcbiAgICAgICAgMTI1LFxuICAgICAgICAzNCxcbiAgICAgICAgMTY2LFxuICAgICAgICAyMjcsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNzQsXG4gICAgICAgIDk2LFxuICAgICAgICA4OCxcbiAgICAgICAgMjAyLFxuICAgICAgICA5MyxcbiAgICAgICAgMTA5LFxuICAgICAgICA2NlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMTIzLFxuICAgICAgICAgIDIsXG4gICAgICAgICAgNzIsXG4gICAgICAgICAgNzAsXG4gICAgICAgICAgMTY3LFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTk0LFxuICAgICAgICAgIDEzOSxcbiAgICAgICAgICA2MyxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDIzOCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMzYsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDUsXG4gICAgICAgICAgMTEwLFxuICAgICAgICAgIDEyNyxcbiAgICAgICAgICAxMzYsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjIxLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgODVcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTQ5LFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDQ0LFxuICAgICAgICAgIDEzMixcbiAgICAgICAgICA5OCxcbiAgICAgICAgICA5MyxcbiAgICAgICAgICA0NixcbiAgICAgICAgICAxMTIsXG4gICAgICAgICAgMTAwLFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICA2NyxcbiAgICAgICAgICAxMDAsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyMzksXG4gICAgICAgICAgNixcbiAgICAgICAgICA1NixcbiAgICAgICAgICAyNDgsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMjQ0LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDE1NSxcbiAgICAgICAgICAyMFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NyxcbiAgICAgICAgODgsXG4gICAgICAgIDMxLFxuICAgICAgICA3OSxcbiAgICAgICAgMjQsXG4gICAgICAgIDQ1LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE3MSxcbiAgICAgICAgMjQxLFxuICAgICAgICAxODYsXG4gICAgICAgIDE2NCxcbiAgICAgICAgMjE5LFxuICAgICAgICAyMTQsXG4gICAgICAgIDI1MixcbiAgICAgICAgNTAsXG4gICAgICAgIDIxNSxcbiAgICAgICAgMTkzLFxuICAgICAgICA0NCxcbiAgICAgICAgMTUsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTYxLFxuICAgICAgICAyMTAsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMzUsXG4gICAgICAgIDIzNyxcbiAgICAgICAgNTQsXG4gICAgICAgIDEwMSxcbiAgICAgICAgMTI3LFxuICAgICAgICAxNDYsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMTQ3LFxuICAgICAgICA4OCxcbiAgICAgICAgMTMxLFxuICAgICAgICAxOCxcbiAgICAgICAgMjMwLFxuICAgICAgICA5OCxcbiAgICAgICAgMjQ2LFxuICAgICAgICAxNDIsXG4gICAgICAgIDU0LFxuICAgICAgICAxNTIsXG4gICAgICAgIDAsXG4gICAgICAgIDcyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTY3LFxuICAgICAgICAyMzksXG4gICAgICAgIDIwMixcbiAgICAgICAgMTYyLFxuICAgICAgICA1OCxcbiAgICAgICAgMTg3LFxuICAgICAgICAxNTcsXG4gICAgICAgIDExNixcbiAgICAgICAgNjcsXG4gICAgICAgIDI3LFxuICAgICAgICA2MixcbiAgICAgICAgMTU2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDEyLFxuICAgICAgICAxOCxcbiAgICAgICAgMTgwLFxuICAgICAgICAxMzcsXG4gICAgICAgIDE3MSxcbiAgICAgICAgNzksXG4gICAgICAgIDEyXG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxNCxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCIxeERVb1FQWEI0UjRNTEtBQ1RSSmtpQnRMSGpJUXNKTUswSG1NSGxoT2V3PVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjkyMzExOTE3MDY0NUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiQkJDRkQ1MjNFNUUyRTU5NTJEOTg0NTRGMEJBRjY1ODVcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI2MTA5MTE3XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTIzMTE5MTcwNjQ1QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJFQThGRjcyMTg5QUI1QkU4Q0M4MDAxMDg3QkUxNDc4MlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjYxMDkxMThcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiNnhBb0l5NnhUaTZlX2Q1bUlrNldJUVwiLFxuICBcInBob25lSWRcIjogXCIzZWI5ZGUzMC0yMTY1LTQzYTctOTAwZi05OGZlZmU5YmQ1NWJcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTM0LFxuICAgICAgMTcsXG4gICAgICAxODksXG4gICAgICAyMDUsXG4gICAgICAyNTAsXG4gICAgICA4NixcbiAgICAgIDE3NSxcbiAgICAgIDIzNSxcbiAgICAgIDIxOCxcbiAgICAgIDI5LFxuICAgICAgMTY4LFxuICAgICAgMjQ3LFxuICAgICAgMTQ4LFxuICAgICAgNjcsXG4gICAgICAxNDUsXG4gICAgICAxMDIsXG4gICAgICA1LFxuICAgICAgMCxcbiAgICAgIDI3LFxuICAgICAgMjIxXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE5OCxcbiAgICAgIDE2OCxcbiAgICAgIDk2LFxuICAgICAgNyxcbiAgICAgIDE3OSxcbiAgICAgIDEwNyxcbiAgICAgIDI0OSxcbiAgICAgIDExLFxuICAgICAgMTAyLFxuICAgICAgMTg5LFxuICAgICAgMTksXG4gICAgICAxOSxcbiAgICAgIDExMyxcbiAgICAgIDE1NCxcbiAgICAgIDI1MCxcbiAgICAgIDE4OSxcbiAgICAgIDE0MSxcbiAgICAgIDcyLFxuICAgICAgNTYsXG4gICAgICAxMzlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiQkI5UlY0R0RcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkyMzExOTE3MDY0NToxM0BzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiMTY4OTI1ODI4NTMwMzg5OjEzQGxpZFwiLFxuICAgIFwibmFtZVwiOiBcIu+8r++9jSDkuYjvvZLwn5SlXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTVQ2ZzdZSEVMV3JpYmNHR0EwZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCI2THFqVndzQWFrbkxUd1c3YUJXQ2h2S0pHTlhzMVlpZ3dIdEc4SUdDOEc0PVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIlVkT0ZjY1M3OGo2R3lrZjlnUFdSak5XTXVkMjB3bXJTL0UvMzNBVVdMMVJqSHkweTYvWmpVMXFBeDVSTXAvQ3lUbWhXVkwxOUVoMVJzZU5kcFJxWENnPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInlJUHRMcU1IWnRSUHJ6bmVvcG52Umd6d01qdkFSOUVQTDd1QzFRTFl2WTBmVVkzWjJoa0lRYzVtblRncDQ0Y21xRHR3Z2c0NW5EQXA5SjEvZVNlMkF3PT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkyMzExOTE3MDY0NToxM0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDIzMixcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMTYzLFxuICAgICAgICAgIDg3LFxuICAgICAgICAgIDExLFxuICAgICAgICAgIDAsXG4gICAgICAgICAgMTA2LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMjEsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDEzNCxcbiAgICAgICAgICAyNDIsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMTkyLFxuICAgICAgICAgIDEyMyxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyNDAsXG4gICAgICAgICAgMTEwXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJhbmRyb2lkXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjYxMDkxMTQsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFOblRcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQU5uVC5qc29uIjogIntcImtleURhdGFcIjpcIlY0azNWdkgyUG1ITytISGlmZm5jUXUyeWZQTCt1NnJVNjVkL2tYdUw5NEk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTk5MjM1OTIzNixcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9Igp9",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
